export const CLAIM_RULES = [
  {
    semanticKey: 'service.full_history',
    category: 'service',
    label: 'Service history',
    patterns: [
      /\bfull\s+service\s+history\b/i,
      /\bcomplete\s+service\s+history\b/i,
      /\bfull(y)?\s+serviced\b/i,
      /\bservice\s+book\s+(complete|stamped)\b/i,
    ],
    evidenceNeeded: 'Dated service invoices and/or service-book entries showing mileage and workshop details.',
    whyItMatters: 'A documented service trail helps confirm maintenance timing and whether mileage progression is plausible.',
    sellerQuestion: 'Can you send dated service invoices or service-book entries showing the mileage and workshop details?',
  },
  {
    semanticKey: 'repair.clutch',
    category: 'repair',
    label: 'Clutch replacement',
    patterns: [
      /\b(new|replaced|replacement)\s+clutch\b/i,
      /\bclutch\s+(was\s+)?replaced\b/i,
      /\bclutch\s+new\b/i,
    ],
    evidenceNeeded: 'Invoice or workshop receipt showing the clutch replacement date, mileage and parts/workshop.',
    whyItMatters: 'A recent clutch replacement can be valuable, but the date and mileage determine how meaningful the claim is.',
    sellerQuestion: 'Do you have the invoice for the clutch replacement, including the date and mileage?',
  },
  {
    semanticKey: 'repair.timing_belt',
    category: 'repair',
    label: 'Timing belt replacement',
    patterns: [
      /\b(new|replaced|replacement)\s+(timing|cam)\s*belt\b/i,
      /\b(timing|cam)\s*belt\s+(was\s+)?replaced\b/i,
    ],
    evidenceNeeded: 'Invoice showing timing-belt kit replacement date, mileage and workshop.',
    whyItMatters: 'Timing-belt replacement intervals can be critical; documentation is more useful than an undated seller statement.',
    sellerQuestion: 'Can you send the invoice for the timing-belt replacement with the date and mileage?',
  },
  {
    semanticKey: 'repair.brakes',
    category: 'repair',
    label: 'Recent brake work',
    patterns: [
      /\b(new|replaced)\s+(front\s+|rear\s+)?(brakes|brake\s+pads|discs|rotors)\b/i,
      /\b(brake\s+pads|discs|rotors)\s+(were\s+)?replaced\b/i,
    ],
    evidenceNeeded: 'Workshop invoice listing replaced brake parts, date and mileage.',
    whyItMatters: 'Brake-work claims are most useful when the replaced axle/parts and timing are documented.',
    sellerQuestion: 'Do you have a workshop invoice for the recent brake work showing which parts were replaced and when?',
  },
  {
    semanticKey: 'history.accident_free',
    category: 'history',
    label: 'Accident-free history',
    patterns: [
      /\b(accident[-\s]?free|never\s+accident(ed)?|no\s+accidents?|unfallfrei)\b/i,
    ],
    evidenceNeeded: 'Vehicle-history documentation plus inspection of body/paint and repair records where available.',
    whyItMatters: '“Accident-free” is difficult to establish from the listing alone; history records and physical inspection provide supporting evidence.',
    sellerQuestion: 'What documentation supports the accident-free claim, and are there any body or paint repairs I should know about?',
  },
  {
    semanticKey: 'inspection.valid',
    category: 'inspection',
    label: 'Valid roadworthiness inspection',
    patterns: [
      /\b(valid\s+(mot|t[uü]v|technical\s+inspection|inspection))\b/i,
      /\b(mot|t[uü]v|technical\s+inspection)\s+(valid|until|through)\b/i,
      /\bcontr[oô]le\s+technique\s+(valide|jusqu['’]?au)\b/i,
    ],
    evidenceNeeded: 'Current roadworthiness/inspection certificate showing date, vehicle identity and any recorded advisories.',
    whyItMatters: 'A current certificate verifies inspection status at a specific date but does not replace an independent pre-purchase inspection.',
    sellerQuestion: 'Can you send the current inspection certificate, including any advisories or observations?',
  },
  {
    semanticKey: 'ownership.one_owner',
    category: 'ownership',
    label: 'Single-owner claim',
    patterns: [
      /\b(one|1|single)\s+owner\b/i,
      /\bfirst\s+owner\b/i,
      /\b1st\s+owner\b/i,
    ],
    evidenceNeeded: 'Registration/title history or equivalent ownership records consistent with the claim.',
    whyItMatters: 'Owner count can affect how the history is interpreted, but the listing itself cannot prove it.',
    sellerQuestion: 'Can you provide ownership or registration records that support the one-owner claim?',
  },
  {
    semanticKey: 'mileage.genuine',
    category: 'mileage',
    label: 'Genuine mileage',
    patterns: [
      /\b(genuine|original|verified|certified)\s+(mileage|kilomet(er|re)s?|km)\b/i,
      /\bmileage\s+(is\s+)?(genuine|verified|certified)\b/i,
    ],
    evidenceNeeded: 'Mileage progression across inspection reports, service invoices and/or official history records.',
    whyItMatters: 'Consistent mileage progression across dated records is stronger evidence than a single odometer reading.',
    sellerQuestion: 'Can you send dated records that show the mileage progression over time?',
  },
  {
    semanticKey: 'identity.vin',
    category: 'identity',
    label: 'VIN available',
    patterns: [
      /\bvin\s+(available|provided|on\s+request)\b/i,
      /\bvehicle\s+identification\s+number\s+(available|provided)\b/i,
    ],
    evidenceNeeded: 'VIN that matches the vehicle and its registration/documentation.',
    whyItMatters: 'A VIN lets the buyer cross-check the vehicle identity against records and documents.',
    sellerQuestion: 'Can you send the VIN so I can cross-check the vehicle identity and records?',
  },
];

export const CATEGORY_LABELS = {
  service: 'Service',
  repair: 'Repair',
  history: 'History',
  inspection: 'Inspection',
  ownership: 'Ownership',
  mileage: 'Mileage',
  identity: 'Identity',
};
